version: "3.7"

services:
  ajuna-node:
    image: demo/node
    build:
      context: .
      dockerfile: Dockerfile.node
    command: ./ajuna --dev --tmp --unsafe-ws-external --unsafe-rpc-external
    ports:
      - 9944:9944

  worker:
    image: demo/worker
    build:
      context: .
      dockerfile: Dockerfile.integritee
    command: /bin/bash -c "
      ./integritee-service init-shard
      && ./integritee-service shielding-key
      && ./integritee-service signing-key
      && ./integritee-service  -u ws://host.docker.internal run --dev --skip-ra"
    ports:
      - 2000:2000
      - 3443:3443
      - 8787:8787
      - 2001:2001
