version: "3.7"

services:
  ajuna-node:
    image: demo/node
    build:
      context: .
      dockerfile: Dockerfile.node
    command: "tail -F /dev/null" 
  worker:
    image: demo/worker
    build:
      context: .
      dockerfile: Dockerfile.integritee
    command: "tail -F /dev/null"
  
  mono:
    depends_on:
      - ajuna-node
      - worker
    image: demo/mono
    build:
      context: .
      dockerfile: Dockerfile.mono
    ports:
      - 9944:9944
      - 2000:2000
      - 3443:3443
      - 8787:8787
      - 2001:2001
    command: ["/bin/bash", "-c", "./launch.sh"]
