version: "3.7"

services:
  ajuna-node:
    image: democonnectfour.azurecr.io/node
    build:
      context: .
      dockerfile: Dockerfile.node
    command: ./ajuna --dev --tmp --unsafe-ws-external --unsafe-rpc-external
    ports:
      - 9944:9944
      - 9933:9933

  worker:
    image: democonnectfour.azurecr.io/worker
    volumes:
      - ./ngrok-stable-linux-amd64.tgz:/proxy/ngrok.tgz
      - ./proxy.sh:/proxy/proxy.sh
    build:
      context: .
      dockerfile: Dockerfile.integritee
    command: /bin/bash -c "
      rm -f light_client_db.bin
      && rm -fr shards
      && rm -fr sidechain_db
      && tar zvfx /proxy/ngrok.tgz
      && ./ngrok authtoken ${AUTHTOKEN} 
      && ./integritee-service init-shard
      && ./integritee-service shielding-key
      && ./integritee-service signing-key
      && sleep 10
      && /proxy/proxy.sh
      && ./integritee-service --ws-external -u ws://ajuna-node run --dev --skip-ra"
    ports:
      - 2000:2000
      - 3443:3443
      - 8787:8787
      - 2001:2001
