version: "3.7"

services:
  ajuna-node:
    image: backend-devel.azurecr.io/node
    build:
      context: ./Ajuna
      dockerfile: docker/Dockerfile
      args:
        - features=solo,skip-ias-check
        - bin=ajuna-solo
    command: --dev --tmp --unsafe-ws-external --unsafe-rpc-external
    ports:
      - 9944:9944
      - 9933:9933

  worker:
    image: backend-devel.azurecr.io/worker
    volumes:
      - ./ngrok-stable-linux-amd64.tgz:/proxy/ngrok.tgz
      - ./proxy.sh:/proxy/proxy.sh
      - ./key.txt:/root/work/worker/bin/key.txt
      - ./spid.txt:/root/work/worker/bin/spid.txt
      - ./demo_connect_four.sh:/root/work/worker/bin/demo_connect_four.sh
    build:
      context: ./worker
      dockerfile: build.Dockerfile
      target: builder
    command: /bin/bash -c "
      cd /root/work/worker/bin
      && rm -f light_client_db.bin
      && rm -fr shards
      && rm -fr sidechain_db
      && tar zvfx /proxy/ngrok.tgz
      && ./ngrok authtoken ${AUTHTOKEN}
      && ./integritee-service init-shard
      && ./integritee-service shielding-key
      && ./integritee-service signing-key
      && sleep 10
      && /proxy/proxy.sh
      && ./integritee-service --ws-external -u ws://ajuna-node run --dev --skip-ra"
    ports:
      - 2000:2000
      - 3443:3443
      - 8787:8787
      - 2001:2001

  polkadot-ui:
    image: jacogr/polkadot-js-apps:latest
    links:
      - ajuna-node
    environment:
      - WS_URL=ws://localhost:9944
    ports:
      - 80:80
